version: '3'
services:
  apigateway-service:
    container_name: lapka_apigateway
    build: .
    image: lapka_apigateway_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lapka_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672